# Generated by Django 4.2.4 on 2023-08-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='client',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='country',
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
