# Generated by Django 4.2.4 on 2023-08-15 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_client_dob_remove_client_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='location',
        ),
        migrations.RemoveField(
            model_name='company',
            name='phone',
        ),
    ]
